FROM jboss/wildfly
# RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent
USER root
RUN yum -y install bash
USER jboss

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c", "../../docs/examples/configs/standalone-rts.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
